routes/front.php
<?php
AdvancedRoute::controller('auth', 'AuthController');
AdvancedRoute::controller('profile', 'ProfileController');
AdvancedRoute::controller('notifications', 'NotificationsController');
AdvancedRoute::controller('roles', 'RolesController');
AdvancedRoute::controller('countries', 'CountriesController');
AdvancedRoute::controller('currencies', 'CurrenciesController');
AdvancedRoute::controller('users', 'UsersController');
AdvancedRoute::controller('posts', 'PostsController');
AdvancedRoute::controller('dashboard', 'DashBoardController');
AdvancedRoute::controller('events', 'EventsController');
AdvancedRoute::controller('groups', 'GroupsController');
AdvancedRoute::controller('programs', 'ProgramsController');
AdvancedRoute::controller('items', 'ItemsController');
AdvancedRoute::controller('contacts', 'ContactsController');
AdvancedRoute::controller('children', 'ChildrenController');
AdvancedRoute::controller('/', 'DashBoardController');

routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

/* Route::get('/', function () {
  return view('welcome');
  });
 */
Route::group(['prefix' => (app()->environment() == 'testing') ? 'en' : LaravelLocalization::setLocale(), 'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath']], function() {
    AdvancedRoute::controller('auth', 'AuthController');
    Route::group(['middleware' => ['auth']], function() {
        AdvancedRoute::controller('profile', 'ProfileController');
        AdvancedRoute::controller('notifications', 'NotificationsController');
        Route::group(['prefix' => 'admin'], function() {
            Route::group(['middleware' => ['isAdmin']], function() {
                AdvancedRoute::controller('roles', 'Admin\RolesController');
                AdvancedRoute::controller('users', 'Admin\UsersController');
                AdvancedRoute::controller('posts', 'Admin\PostsController');
                AdvancedRoute::controller('pages', 'Admin\PagesController');
                AdvancedRoute::controller('categories', 'Admin\CategoriesController');
                AdvancedRoute::controller('comments', 'Admin\CommentsController');
                AdvancedRoute::controller('likes', 'Admin\LikesController');
                AdvancedRoute::controller('rates', 'Admin\RatesController');
                AdvancedRoute::controller('configs', 'Admin\ConfigsController');
                AdvancedRoute::controller('search', 'Admin\SearchController');
                AdvancedRoute::controller('translator', 'Admin\TranslatorController');
                AdvancedRoute::controller('options', 'Admin\OptionsController');
                AdvancedRoute::controller('messages', 'Admin\MessagesController');
                AdvancedRoute::controller('sections', 'Admin\SectionsController');
                AdvancedRoute::controller('courses', 'Admin\CoursesController');
                AdvancedRoute::controller('contacts', 'Admin\ContactsController');
                AdvancedRoute::controller('units', 'Admin\UnitsController');
                AdvancedRoute::controller('lectures', 'Admin\LecturesController');
                AdvancedRoute::controller('menu', 'Admin\MenuController');
                AdvancedRoute::controller('ajax', 'Admin\AjaxController');
            });
            AdvancedRoute::controller('/', 'Admin\DashBoardController');
        });
        Route::group(['middleware' => ['isTeacher'], 'prefix' => 'teacher'], function() {
            AdvancedRoute::controller('/', 'Teacher\DashBoardController');
            AdvancedRoute::controller('courses', 'Teacher\CoursesController');
            AdvancedRoute::controller('coupons', 'Teacher\CouponsController');
            AdvancedRoute::controller('comments', 'Teacher\CommentsController');
            AdvancedRoute::controller('likes', 'Teacher\LikesController');
            AdvancedRoute::controller('rates', 'Teacher\RatesController');
            AdvancedRoute::controller('units', 'Teacher\UnitsController');
            AdvancedRoute::controller('lectures', 'Teacher\LecturesController');
        });
        AdvancedRoute::controller('/', 'Teacher\DashBoardController');
        AdvancedRoute::controller('dashboard', 'DashboardController');
        AdvancedRoute::controller('comments', 'CommentsController');
        AdvancedRoute::controller('ajax', 'AjaxController');
    });
    AdvancedRoute::controller('/orders', 'OrdersController');
    AdvancedRoute::controller('/learn', 'LearnController');
    AdvancedRoute::controller('/favourites', 'FavouritesController');
    AdvancedRoute::controller('/courses', 'CoursesController');
    AdvancedRoute::controller('/posts', 'PostsController');
    AdvancedRoute::controller('/bio', 'BioController');
    AdvancedRoute::controller('/messages', 'MessagesController');
    AdvancedRoute::controller('/contacts', 'ContactsController');
    AdvancedRoute::controller('/pages', 'PagesController');
    Route::get('/about', 'PagesController@getAbout');
    Route::get('/contact', 'PagesController@getContact');
    AdvancedRoute::controller('/', 'HomeController');
});


Route::prefix('api')->group(function () {
    require_once __DIR__ . '/api.php';
});

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon;

class Menu extends \App\Models\BaseModel {

    use SoftDeletes,
        \App\Models\Traits\CreatedBy,
        \App\Models\Traits\HasAttach,
        \Laravel\Scout\Searchable,
        \Spatie\Translatable\HasTranslations;

    ///////////////////////////// has translation
    public $translatable = ['title'];
    protected $table = "menu";
    protected $guarded = [
        'deleted_at',
        'image',
        'logged_user'
    ];
    protected $hidden = [
        'deleted_at',
    ];
    protected static $attachFields = [
        'image' => [
            'sizes' => ['small' => 'crop,240x180', 'large' => 'resize,720x540'],
            'path' => 'uploads'
        ],
    ];
    public $rules = [
        'title' => 'required',
    ];

    public function toSearchableArray() {
        $array = [
            'id' => $this->id,
            'title' => $this->title,
        ];
        return $array;
    }

    public static function boot() {
        parent::boot();
        static::created(function ($row) {
            if (!request()->hasFile('image') && !$row->image) {
                $image = generateImage($row->title, ['small' => '300x211', 'large' => '720x540']);
                $data['image'] = $image;
                \DB::table('posts')->where('id', $row->id)->update($data);
            }
        });
    }

    public function top() {
        return $this->belongsTo(Menu::class, 'parent_id')->withTrashed()->withDefault();
    }

    public function childs() {
        return $this->hasMany(Menu::class, 'parent_id');
    }

    public function page() {
        return $this->belongsTo(Page::class, 'page_id')->withTrashed()->withDefault();
    }

    public function scopeActive($query) {
        return $query->where('is_active', '=', 1);
    }

    public function getData() {
        return $this->when(request('category_id'), function($q) {
                            return $q->where('category_id', request('category_id'));
                        })->when(request('title'), function($q) {
                            return $q->where('title', 'LIKE', '%' . request('title') . '%');
                        })
                        ->when(request('tags'), function($q) {
                            return $q->where('tags', 'LIKE', '%' . request('tags') . '%');
                        });
    }

    public function export($rows, $fileName) {
        if ($rows) {
            foreach ($rows as $row) {
                unset($object);
                $object['ID'] = $row->id;
                $object['Title'] = $row->title;
                $object['Order field'] = $row->order_field;
                $object['Is Active'] = ($row->is_active) ? trans('app.Yes') : trans('app.No');
                $object['Created at'] = $row->created_at;
                $labels = array_keys($object);
                $data[] = $object;
            }
            export($data, $labels, $fileName);
        }
    }

    public function getLinkAttribute() {
        return app()->make("url")->to('/') . '/' . lang() . '/pages/details/' . $this->id . '/' . $this->slug;
    }

    public function getTitleLimitedAttribute() {
        return str_limit($this->title, 35);
    }

    public function getContentLimitedAttribute() {
        return str_limit(strip_tags($this->content), 60);
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Authenticatable {

    use SoftDeletes,
        \App\Models\Traits\CreatedBy,
        \App\Models\Traits\HasAttach,
        \Laravel\Scout\Searchable,
        \Spatie\Translatable\HasTranslations;

    protected $table = "users";
    protected $guarded = [
        'deleted_at',
        'logged_user',
        'image',
        'teams',
    ];
    protected $hidden = [
        'password',
        'remember_token',
        'confirm_token',
        'confirmed',
        'is_active',
        'is_admin',
        'created_by',
        'updated_at',
        'deleted_at',
        'language'
    ];
    protected $appends = ['is_admin', 'is_super_admin', 'title'];
    public $translatable = ['bio', 'meta_description', 'meta_keywords'];
    ///////////////////////////// has attach
    protected static $attachFields = [
        'image' => [
            'sizes' => ['small' => 'crop,240x180', 'large' => 'resize,720x540'],
            'path' => 'uploads'
        ],
    ];
    public $rules = [
        'name' => 'required',
        'email' => 'required|email|unique:users,email',
        'mobile' => 'required|mobile',
        'password' => "required|confirmed|min:8",
        'image' => 'nullable|image|max:4000'
    ];

    public function toSearchableArray() {
        $array = [
            'id' => $this->id,
            'name' => $this->name,
            'email' => $this->email,
            'mobile' => $this->mobile,
        ];
        return $array;
    }

    public static function boot() {
        parent::boot();
        static::created(function ($row) {
            if (!request()->hasFile('image') && !$row->image) {
                $image = generateImage($row->title);
                $data['image'] = $image;
                \DB::table('users')->where('id', $row->id)->update($data);
            }
            \App\Jobs\SendRegisterEMail::dispatch($row);
        });
    }

    public function getIsAdminAttribute() {
        return ($this->role_id);
    }

    public function getIsSuperAdminAttribute() {
        return ($this->role_id == 1);
    }

    public function getTitleAttribute() {
        return $this->name;
    }

    public function notifications() {
        return $this->hasMany(Notification::class, 'to_id');
    }

    public function role() {
        return $this->belongsTo(Role::class, 'role_id')->withTrashed()->withDefault();
    }

    public function tokens() {
        return $this->hasMany(Token::class);
    }

    public function favourites() {
        return $this->hasMany(Favourite::class)->with(['course']);
    }

    public function orders() {
        return $this->hasMany(Order::class, 'created_by')->with(['course']);
    }
    public function ordersList() {
        return $this->hasMany(Order::class, 'created_by')->pluck('course_id')->toArray();
    }

    public function courses() {
        return $this->hasMany(Course::class, 'created_by');
    }

    public function getGenders() {
        return \App\Models\Option::where('type', 'gender')->pluck('title', 'id');
    }

    public function getRoles() {
        return \App\Models\Role::where('id', '!=', 1)->pluck('title', 'id');
    }

    public function setPasswordAttribute($value) {
        if (trim($value)) {
            $this->attributes['password'] = bcrypt(trim($value));
        }
    }

    public function setConfirmTokenAttribute($value) {
        if (trim($value)) {
            $this->attributes['confirm_token'] = md5(trim($value)) . md5(time());
        }
    }

    public function scopeActive($query) {
        return $query->where('is_active', '=', 1)->where('confirmed', 1);
    }

    public function scopeIsTeacher($query) {
        return $query->where('is_teacher', '=', 1)->where('confirmed', 1);
    }

    public function getData() {
        return $this->with(['role', 'creator']);
    }

    public function rates() {
        return $this->morphMany(Rate::class, 'rateable');
    }

    public function getrateAttribute() {
        if ($this->rates->count() > 0)
            return floor($this->rates->sum('value') / $this->rates->count());
        else
            return 0;
    }

    public function export($rows, $fileName) {
        if ($rows) {
            foreach ($rows as $row) {
                unset($object);
                $object['ID'] = $row->id;
                $object['Name'] = $row->name;
                $object['Email'] = $row->email;
                $object['Mobile'] = $row->mobile;
                $object['Is Admin'] = ($row->is_admin) ? 'Yes' : 'No';
                $object['Created at'] = $row->created_at;
                $labels = array_keys($object);
                $data[] = $object;
            }
            export($data, $labels, $fileName);
        }
    }

    public function getBioLimitedAttribute() {
        return str_limit(strip_tags($this->bio), 60);
    }

    public function getLinkAttribute() {
        $slug = slug($this->name);
        return app()->make("url")->to('/') . '/' . lang() . '/bio/details/' . $this->id . '/' . $slug;
    }

    public function comments() {
        return $this->morphMany(Comment::class, 'commentable');
    }

}

app/Http/Controllers/CoursesController.php
<?php

namespace App\Http\Controllers;

class CoursesController extends \App\Http\Controllers\Controller {

    public $module;

    public function __construct(\App\Models\Course $model) {
        $this->module = 'courses';
        $this->views = 'front.' . $this->module;
        $this->model = $model;
        $this->middleware('auth')->only(['getMyCourses']);
    }

    public function getMyCourses(\App\Models\Course $course) {
        $data['page_title'] = trans('app.My courses');
        $data['rows'] = $course->getData()->whereIn('id',auth()->user()->ordersList())->active()->latest()->paginate(env('PAGE_LIMIT', 10));
        return view($this->views . '.my-courses', $data);
    }

    public function getIndex() {
        $data['page_title'] = trans('app.Courses');
        $data['rows'] = $this->model->getData()->active()->latest()->paginate(env('PAGE_LIMIT', 10));
        return view($this->views . '.index', $data);
    }

    public function getDetails($id, $slug = NULL, \App\Models\Course $post) {
        $data['row'] = $this->model->findOrFail($id);
        if (@auth()->user() && in_array($id,@auth()->user()->ordersList())) {
            return redirect('learn?course_id='.$id);
        }
        $data['page_title'] = $data['row']->title;
        $data['relatedCourses'] = $post->getData()->where('section_id', $data['row']->section_id)->active()->where('id', '!=', $id)->latest()->take(3)->get();
        return view($this->views . '.details', $data);
    }

}

resources/views/front/courses/counts.blade.php
<div class="single-item-content">
    <div class="single-item-comment-view">
        <span><i class="zmdi zmdi-eye"></i>{{$row->views}}</span>
        <span><i class="zmdi zmdi-comments"></i>{{$row->comments->count()}}</span>
        <span>
            <a href="favourites/add/{{$row->id}}"><i class="zmdi zmdi-favorite"></i></a>
        </span>
    </div>
    @if($row->rate)
    <div class="single-item-rating">
        @for($i=1; $i<=$row->rate; $i++)
        <i class="zmdi zmdi-star"></i>
        @endfor
        @for($i=1; $i<=5-$row->rate; $i++)
        <i class="zmdi zmdi-star-outline"></i>
        @endfor
    </div>
    @endif
</div>  

resources/views/front/courses/details.blade.php
@extends('front.layouts.master')
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="section-title-wrapper">
            <div class="section-title mt-25">
                <h3>{{$page_title}}</h3>
                <p></p>
            </div>
        </div>
    </div>
</div>
<div class="course-details-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-12 col-12">
                <div class="course-details-content">
                    <div class="single-course-details">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="overlay-effect">
                                    <a href="#">
                                        <img src="uploads/large/{{$row->image}}" alt="{{$row->title}}">
                                    </a>
                                </div>
                            </div>  
                            <div class="col-md-6">
                                <div class="single-item-text">
                                    <div class="single-item-text-info">
                                        <span>{{trans('app.By')}}: <span>{{$row->creator->name}}</span></span>
                                        <span>{{trans('app.Date')}}: <span>{{str_limit($row->created_at,10,false)}}</span></span><br>
                                        <span>{{trans('app.Has certificate')}}: <span>{{($row->has_certificat)?trans('app.Yes'):trans('app.No')}}</span></span>
                                        <span>{{trans('app.Level')}}: <span>{{$row->level->title}}</span></span><br>
                                        <span>{{trans('app.Language')}}: <span>{{$row->language->title}}</span></span>
                                    </div>

                                    <div class="course-text-content">
                                        <p>{!! $row->content !!}</p>
                                        <p>
                                            <a href="{{lang()}}/orders/add/{{$row->id}}" class="btn btn-theme btn-success">{{trans('app.Buy')}}
                                            </a>
                                        </p>
                                        <div class="row news-details-content ">

                                            <div class="social-links">
                                                <span>{{trans('app.Share')}}:</span>
                                                <a href="https://facebook.com/sharer/sharer.php?u={{$row->link}}" target="_blank"><i class="zmdi zmdi-facebook"></i></a>
                                                <a href="https://twitter.com/intent/tweet?url={{$row->link}}" target="_blank"><i class="zmdi zmdi-twitter"></i></a>
                                                <a href="https://www.linkedin.com/shareArticle?url={{$row->link}}" target="_blank"><i class="zmdi zmdi-linkedin"></i></a>
                                                <a href="https://web.whatsapp.com/send?text={{$row->link}}" target="_blank"><i class="zmdi zmdi-whatsapp"></i></a>
                                            </div>
                                        </div>
                                    </div>   

                                    @include('front.courses.counts') 
                                </div>
                            </div> 

                        </div>     
                    </div>
                    <div class="comments contact-form-area">
                        @if(auth()->user())
                        <h4 class="title">{{trans('app.Write your comment')}}</h4>
                        <form id="contact-form" action="{{lang()}}/comments?commentable_id={{$row->id}}&type=course" method="post">
                            <div class="row">
                                <div class="col-md-12">
                                    <textarea name="content" cols="30" rows="10" placeholder="{{trans('app.Message')}}"></textarea>
                                    <button type="submit" class="button-default">{{trans('app.SUBMIT')}}</button>
                                </div>
                            </div>
                        </form>
                        @else
                        <h4 class="title">{{trans('app.Need to write your comment')}} <a href="{{lang()}}/auth/login">{{trans('app.Login')}}</a></h4>
                        @endif
                    </div>
                    @php
                    $comments=$row->comments()->with(['replies'])->where('reply_to',NULL)->latest()->get();
                    @endphp
                    @if($comments)
                    <div class="comments">
                        <h4 class="title">{{trans('app.Comments')}}</h4>
                        @foreach($comments as $comment)
                        <div class="single-comment">
                            <div class="author-image">
                                <img src="uploads/small/{{$comment->creator->image}}" alt="{{$comment->creator->name}}-{{$comment->id}}">
                            </div>
                            <div class="comment-text">
                                <div class="author-info">
                                    <h4><a href="#">{{$comment->creator->name}}</a></h4>
                                    <span class="reply" data-id="reply_box_{{$comment->id}}"><a href=#">{{trans('app.Reply')}}</a></span>
                                    <span class="comment-time">{{trans('app.Posted on')}} {{$comment->created_at}} /</span>
                                </div>
                                <p>{{$comment->content}}</p>
                                <div class="comment_box_reply" id="reply_box_{{$comment->id}}" style="display: none;">
                                    <div class="comments contact-form-area">
                                        @if(auth()->user())
                                        <form id="contact-form" action="{{lang()}}/comments/reply?reply_to={{$comment->id}}" method="post">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <textarea name="content" cols="30" rows="10" placeholder="{{trans('app.Message')}}"></textarea>
                                                    <button type="submit" class="button-default">{{trans('app.SUBMIT')}}</button>
                                                </div>
                                            </div>
                                        </form>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        @foreach($comment->replies()->latest()->get() as $c)
                        <div class="single-comment comment-reply">
                            <div class="author-image">
                                <img src="uploads/small/{{$c->creator->image}}" alt="{{$c->creator->name}}">
                            </div>
                            <div class="comment-text">
                                <div class="author-info">
                                    <h4><a href="#">{{$c->creator->name}}</a></h4>
                                    <span class="comment-time">{{trans('app.Posted on')}} {{$comment->created_at}}</span>
                                </div>
                                <p>{{$c->content}}</p>
                            </div>
                        </div>
                        @endforeach
                        @endforeach
                    </div>
                    @endif
                </div>    
            </div>
            <div class="col-lg-3 col-md-12 col-12">
                <div class="sidebar-widget">
                    <div class="single-sidebar-widget">
                        <div class="tution-wrapper">
                            <div class="tution-fee">
                                <h1>{{$row->price}} <span class="currency">{{trans('app.EGP')}}</span></h1>
                            </div>
                            <div class="tutor-image">
                                <img src="uploads/small/{{$row->creator->image}}" alt="{{$row->creator->name}}">
                            </div>
                            <div class="single-teacher-text">
                                <h3><a href="{{lang()}}/bio/{{$row->created_by}}">{{$row->creator->name}}</a></h3>
                                <p>{{$row->creator->bio_limited}}</p>
                                <div class="single-item-comment-view">
                                    <span>{{$row->creator->courses()->active()->count()}} {{trans('app.Courses')}}</span>                          </div>
                                @if($rate=$row->creator->rate)
                                <div class="single-item-rating">
                                    @for($i=1; $i<=$rate; $i++)
                                    <i class="zmdi zmdi-star"></i>
                                    @endfor
                                    @for($i=1; $i<=5-$rate; $i++)
                                    <i class="zmdi zmdi-star-outline"></i>
                                    @endfor
                                </div>
                                @endif
                            </div>
                        </div>
                    </div>
                    @if($row->tags)
                    <div class="single-sidebar-widget">
                        <h4 class="title">{{trans('app.Search by Tags')}}</h4>
                        <ul class="tags">
                            @foreach(explode(',',$row->tags) as $tag)
                            <li><a href="{{lang()}}/courses?tags={{$tag}}">{{$tag}}</a></li>
                            @endforeach
                        </ul>
                    </div>
                    @endif
                    @if($relatedCourses)
                    <div class="single-sidebar-widget">
                        <h4 class="title">{{trans('app.Related Courses')}}</h4>
                        @foreach($relatedCourses as $item)
                        <div class="single-item">
                            <div class="single-item-image overlay-effect">
                                <a href="{{$item->link}}">
                                    <img alt="{{$item->title}}" src="uploads/small/{{$item->image}}">
                                </a>
                            </div>
                            <div class="single-item-text">
                                <h4><a href="{{$item->link}}">{{$item->title_limited}}</a></h4>
                                <div class="single-item-text-info">
                                    <span>{{trans('app.By')}}: {{$item->creator->name}}<span></span></span>
                                    <span>{{trans('app.Date')}}: <span>{{str_limit($item->created_at,10,false)}}</span></span>
                                </div>
                                <p>{{$item->content_limited}}</p>
                                @include('front.courses.counts',['row'=>$item])
                            </div>
                            <div class="button-bottom">
                                <a href="{{lang()}}/orders/add/{{$item->id}}" class="btn btn-theme btn-success">{{trans('Buy')}}
                                </a>
                            </div>
                        </div>
                        @endforeach
                    </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>
@endsection


@push('js')
<script>
    $(function () {
        $('.reply').on('click', function () {
            var id = $(this).attr('data-id');
            $('#' + id).toggle();
            return false;
        });
    });
</script>
@endpush

resources/views/front/courses/index.blade.php
@extends('front.layouts.master')

@section('content')
<div class="course-area section-padding course-page">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="section-title-wrapper">
                    <div class="section-title">
                        <h3>{{$page_title}}</h3>
                        <p></p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row mt-40 mb-40">
            @if (!$rows->isEmpty())
            @foreach ($rows as $row)
            @include('front.courses.single')
            @endforeach
            <div class="container">
                <div class="paganition-center center">
                    {!! $rows->appends(['created_by'=>request('created_by'),'category_id'=>request('category_id')])->render() !!}
                </div>
            </div>
            @else
            {{trans("app.There is no results")}}
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/front/courses/single.blade.php
<div class="col-lg-4 col-md-6 col-12">
    <div class="single-item">
        <div class="single-item-image overlay-effect">
            <a href="{{$row->link}}">
                <img src="uploads/small/{{$row->image}}" alt="{{$row->title}}">
            </a>
        </div>
        <div class="single-item-text">
            <h4><a href="{{$row->link}}">{{$row->title}}</a></h4>
            <div class="single-item-text-info">
                <span>{{trans('app.By')}}: <span>{{$row->creator->name}}</span></span>
                <span>{{trans('app.Date')}}: <span>{{$row->created_at->format('F j, Y')}}</span></span>
            </div>
             <div class="single-item-comment-view">
                <span><i class="zmdi zmdi-settings"></i><a href="{{lang()}}/courses?section_id={{$row->section_id}}">{{$row->section->title}}</a></span>
            </div>
            <p>{{$row->content_limited}}</p>
            @include('front.courses.counts')
        </div>
        <div class="button-bottom">
            {!! $row->order_button !!}
        </div>
    </div>
</div>